
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "lljiqniebnmfbytbkjkv"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
# Maximum rows returns from a view, table, or stored procedure. Defaults to 1000.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by the local database to accept connections.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's.
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100
pool_size = 5

[realtime]
enabled = true
ip_version = "IPV4"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually delivered, emails are
# caught and can be viewed from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# Port to use for the storage URL.
port = 54327
# If file uploads require authentication. Set to `false` to enable anonymous uploads.
file_size_limit = "500KiB"

[auth]
enabled = true
# Port to use for the auth URL.
port = 54328
# Major version of the auth server
major_version = 2

[auth.email]
# Allow email-based sign-ups to your project.
enable_signup = true
# Allow users to sign up using a different email than the email that was used for the initial invitation.
restrict_signup_email = false
# Allow inviting users who have not yet signed up.
enable_confirmations = false

# Automated testing configuration. Supabase uses these values to configure the
# test runner for various client libraries.
[testing]
db_url = "postgres://postgres:postgres@localhost:54322/postgres"
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
base_url = "http://127.0.0.1:54321"

# Configure Edge Functions.
[edge_functions]
enabled = true
port = 54333

# Configure edge functions
[functions.chatbot]
verify_jwt = true

[functions.cleanup-screenshots]
verify_jwt = true

[functions.increment-ad-spend]
verify_jwt = true

[functions.notifications]
verify_jwt = true

[functions.rate-limit-check]
verify_jwt = true

[functions.database-cleanup]
verify_jwt = true

