
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    'welcome': 'Welcome',
    'login': 'Login',
    'signup': 'Signup',
    'dashboard': 'Dashboard',
    'products': 'Products',
    'orders': 'Orders',
    'profile': 'Profile',
    'logout': 'Logout',
    'home': 'Home',
    'shops': 'Shops',
    'features': 'Features',
    'blog': 'Blog',
    'about': 'About',
    'messages': 'Messages',
    'favorites': 'Favorites',
    'analytics': 'Analytics',
    'settings': 'Settings',
    
    // Auth
    'email': 'Email',
    'password': 'Password',
    'phone': 'Phone Number',
    'confirmPassword': 'Confirm Password',
    'forgotPassword': 'Forgot Password?',
    'rememberMe': 'Remember Me',
    'alreadyHaveAccount': 'Already have an account?',
    'dontHaveAccount': "Don't have an account?",
    'createAccount': 'Create Account',
    'loginToAccount': 'Login to Your Account',
    
    // Roles
    'admin': 'Admin',
    'wholesaler': 'Wholesaler',
    'seller': 'Seller',
    'pending': 'Pending',
    'selectRole': 'Select Your Role',
    
    // Featured Products
    'featuredProducts.title': 'Featured Products',
    'featuredProducts.description': 'Discover top-quality products from verified suppliers across Pakistan',
    'featuredProducts.viewAll': 'View All Products',
    'featuredProducts.sample': 'Sample',
    'featuredProducts.reviews': 'Reviews',
    'featuredProducts.moq': 'MOQ',
    'featuredProducts.viewDetails': 'View Details',
    'featuredProducts.startJourney': 'Start Your Business Journey',
    'featuredProducts.noProducts': 'No featured products available',
    
    // Why Choose Us
    'whyChoose.title': 'Why Choose PakMandi?',
    'whyChoose.description': 'Designed specifically for Pakistani businesses with local payment methods and regional expertise',
    'whyChoose.wholesalers.title': 'For Wholesalers',
    'whyChoose.wholesalers.description': 'Create shops, list products, and reach retailers across Pakistan',
    'whyChoose.wholesalers.benefit1': 'Unlimited product listings',
    'whyChoose.wholesalers.benefit2': 'Advanced analytics',
    'whyChoose.wholesalers.benefit3': 'Promotional ads',
    'whyChoose.sellers.title': 'For Sellers',
    'whyChoose.sellers.description': 'Source quality products directly from verified wholesalers',
    'whyChoose.sellers.benefit1': 'Bulk pricing',
    'whyChoose.sellers.benefit2': 'Quick ordering',
    'whyChoose.sellers.benefit3': 'Inventory management',
    'whyChoose.secure.title': 'Secure Trading',
    'whyChoose.secure.description': 'End-to-end security with verified businesses and secure payments',
    'whyChoose.secure.benefit1': 'Business verification',
    'whyChoose.secure.benefit2': 'Secure payments',
    'whyChoose.secure.benefit3': 'Dispute resolution',
    
    // Call to Action
    'cta.title': 'Ready to Transform Your Business?',
    'cta.description': 'Join Pakistan\'s fastest-growing B2B marketplace. Get started in minutes with our simple registration process.',
    'cta.createAccount': 'Create Free Account',
    'cta.exploreMarketplace': 'Explore Marketplace',
    
    // Dashboard
    'totalOrders': 'Total Orders',
    'pendingOrders': 'Pending Orders',
    'completedOrders': 'Completed Orders',
    'totalRevenue': 'Total Revenue',
    'myShops': 'My Shops',
    'myProducts': 'My Products',
    'browseShops': 'Browse Shops',
    'createShop': 'Create Shop',
    'addProduct': 'Add Product',
    'viewAll': 'View All',
    
    // Products
    'searchProducts': 'Search products...',
    'browseProducts': 'Browse Products',
    'productName': 'Product Name',
    'price': 'Price',
    'quantity': 'Quantity',
    'category': 'Category',
    'description': 'Description',
    'addToCart': 'Add to Cart',
    'outOfStock': 'Out of Stock',
    'inStock': 'In Stock',
    'minOrderQuantity': 'Minimum Order Quantity',
    
    // Orders
    'orderDetails': 'Order Details',
    'orderStatus': 'Order Status',
    'orderDate': 'Order Date',
    'deliveryAddress': 'Delivery Address',
    'paymentMethod': 'Payment Method',
    'totalAmount': 'Total Amount',
    'placeOrder': 'Place Order',
    'cancelOrder': 'Cancel Order',
    'confirmOrder': 'Confirm Order',
    'rejectOrder': 'Reject Order',
    
    // Order Form
    'createOrder': 'Create Order',
    'productTotal': 'Product Total',
    'grandTotal': 'Grand Total',
    'buyerInformation': 'Buyer Information',
    'fullName': 'Full Name',
    'pakistaniMobileNumber': 'Pakistani Mobile Number',
    'validPakistaniMobile': 'Valid Pakistani mobile number',
    'streetAddress': 'Street Address',
    'shippingDetails': 'Shipping Details',
    'shippingCost': 'Shipping Cost',
    'estimatedDelivery': 'Estimated Delivery',
    'standardShipping': 'Standard shipping',
    'bankTransferDetails': 'Bank Transfer Details',
    'bank': 'Bank',
    'accountNumber': 'Account Number',
    'accountTitle': 'Account Title',
    'transferExactAmount': 'Transfer the exact amount (PKR {amount}) and upload the payment screenshot below',
    'paymentScreenshot': 'Payment Screenshot',
    'clickToUpload': 'Click to upload payment screenshot',
    'maxFileSize': 'PNG, JPG up to {size}',
    'creatingOrder': 'Creating Order...',
    'enterFullName': 'Enter your full name',
    'enterPhoneNumber': 'Enter phone number',
    'enterStreetAddress': 'Enter street address',
    'selectPaymentMethod': 'Select payment method',
    'loadingPaymentMethods': 'Loading payment methods...',
    'noPaymentMethods': 'No payment methods available for this shop. Please contact the wholesaler to set up payment methods.',
    'jazzcashDetails': 'JazzCash Details',
    'easypaisaDetails': 'EasyPaisa Details',
    'mobileNumber': 'Mobile Number',
    'sendToJazzcash': 'Send PKR {amount} to this JazzCash number and upload the payment screenshot',
    'sendToEasypaisa': 'Send PKR {amount} to this EasyPaisa number and upload the payment screenshot',
    'days': 'days',
    
    // Shops
    'shopName': 'Shop Name',
    'shopAddress': 'Shop Address',
    'contactNumber': 'Contact Number',
    'businessType': 'Business Type',
    'postalCode': 'Postal Code',
    'city': 'City',
    'province': 'Province',
    
    // Messages
    'typeMessage': 'Type your message...',
    'send': 'Send',
    'newMessage': 'New Message',
    'conversations': 'Conversations',
    
    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'edit': 'Edit',
    'delete': 'Delete',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'yes': 'Yes',
    'no': 'No',
    'confirm': 'Confirm',
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'update': 'Update',
    'refresh': 'Refresh',
    'downloadReport': 'Download Report',
    'print': 'Print',
    'export': 'Export',
    'import': 'Import',
    
    // Shipping
    'shipping': 'Shipping',
    'shippingConfiguration': 'Shipping Configuration',
    'shippingMethod': 'Shipping Calculation Method',
    'flatRate': 'Flat Rate',
    'weightBased': 'Weight Based',
    'cityBased': 'City Based',
    'freeAboveAmount': 'Free Above Amount',
    'flatRateCost': 'Flat Shipping Rate',
    'freeShippingAbove': 'Free Shipping Above',
    'baseRate': 'Base Rate',
    'perKgRate': 'Per KG Rate',
    'estimatedDeliveryDays': 'Estimated Delivery Days',
    'expressShipping': 'Express Shipping Option',
    'expressCost': 'Express Cost',
    'expressDeliveryDays': 'Express Delivery Days',
    'enableShipping': 'Enable Shipping Configuration',
    'saveShippingConfig': 'Save Shipping Configuration',
    'shippingConfigDescription': 'Configure how shipping costs are calculated for your shop',
    'loadingShippingConfig': 'Loading shipping configuration...',
    'saving': 'Saving...',
    'noShopsYet': "You don't have any shops yet. Create a shop first to configure shipping.",
    
    // Languages
    'english': 'English',
    'urdu': 'اردو',
    
    // Footer
    'allRightsReserved': 'All rights reserved',
    'privacyPolicy': 'Privacy Policy',
    'termsOfService': 'Terms of Service',
    'contactUs': 'Contact Us',
    
    // Dashboard Stats
    'totalProducts': 'Total Products',
    'activeOrders': 'Active Orders',
    'customers': 'Customers',
    'ordersPlaced': 'Orders Placed',
    'totalSpent': 'Total Spent',
    'favoriteShops': 'Favorite Shops',
    'totalUsers': 'Total Users',
    'platformRevenue': 'Platform Revenue',
    'growthRate': 'Growth Rate',
    'fromLastMonth': 'from last month',
    
    // Products
    'noProductsYet': 'No products yet',
    'startAddingProducts': 'Start by adding your first product to your shop.',
    'hideInactiveProducts': 'Hide Inactive Products',
    'showInactiveProducts': 'Show Inactive Products',
    'hide': 'Hide',
    'show': 'Show',
    'inactive': 'Inactive',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'unknown': 'Unknown',
    'failedToLoadProducts': 'Failed to load products',
    'moqPieces': 'MOQ: {moq} pieces',
    
    // Shops
    'noShopsFound': 'No shops found',
    'create': 'Create',
    'createFirstShop': 'Create your first shop to start selling products on our platform.',
    'createYourFirstShop': 'Create Your First Shop',
    'verified': 'Verified',
    'createNewShop': 'Create New Shop',
    'enterShopName': 'Enter shop name',
    'enterCompleteAddress': 'Enter complete shop address',
    'shopLogo': 'Shop Logo (optional, max 5MB)',
    'creating': 'Creating...',
    'fileTooLarge': 'File too large',
    'logoMaxSize': 'Logo image must be less than 5MB',
    'invalidFileType': 'Invalid file type',
    'logoMustBeImage': 'Logo must be an image file',
    'shopCreatedSuccessfully': 'Shop created successfully!',
    'failedToCreateShop': 'Failed to create shop. Please try again.',
    'editShopDetails': 'Edit Shop Details',
    'selectCity': 'Select city',
    'updating': 'Updating...',
    'updateShop': 'Update Shop',
    'shopUpdated': 'Shop updated',
    'shopUpdatedSuccessfully': 'Your shop information has been updated successfully.',
    'failedToUpdateShop': 'Failed to update shop. Please try again.',
    'selectImageSmaller': 'Please select an image smaller than 5MB.',
    'browseWholesaleShops': 'Browse Wholesale Shops',
    'discoverVerifiedSuppliers': 'Discover verified wholesale suppliers across Pakistan',
    'searchShops': 'Search shops by name, location, or contact...',
    'clear': 'Clear',
    'loadingShops': 'Loading shops...',
    'noShopsMatchSearch': 'No shops match your search. Try different keywords.',
    'noShopsAvailable': 'There are no shops available at the moment.',
    'viewProducts': 'View Products',
    'productsAvailable': 'products available',
    
    // Profile
    'myProfile': 'My Profile',
    'manageAccountInfo': 'Manage your account information and preferences',
    'completed': 'Completed',
    'accountType': 'Account Type',
    
    // Orders
    'noOrders': 'No orders yet',
    'all': 'All',
    'attention': 'Attention',
    'active': 'Active',
    'confirmed': 'Confirmed',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'searchOrders': 'Search orders...',
    'filterByStatus': 'Filter by status',
    'statusUpdated': 'Status Updated',
    'orderStatusChanged': 'Order status changed to {status}',
    'failedToUpdateStatus': 'Failed to update order status',
    'failedToFetchOrders': 'Failed to fetch orders. Please try again.',
    
    // Analytics
    'overview': 'Overview',
    'detailed': 'Detailed',
    'performance': 'Performance',
    'views': 'Views',
    'revenue': 'Revenue',
    'dailyActivity': 'Daily Activity',
    'ordersByStatus': 'Orders by Status',
    'topProducts': 'Top Products',
    
    // Product Dialog
    'createProduct': 'Create Product',
    'editProduct': 'Edit Product',
    'basicInfo': 'Basic Info',
    'detailedInfo': 'Detailed Info',
    'images': 'Images',
    'variations': 'Variations',
    'pricing': 'Pricing',
    'uploadImages': 'Upload Images',
    'selectShop': 'Select Shop',
    'enterProductName': 'Enter product name',
    'enterPrice': 'Enter price',
    'enterDescription': 'Enter product description',
    'selectCategory': 'Select Category',
    'productActive': 'Active',
    'moq': 'Minimum Order Quantity (MOQ)',
    'brand': 'Brand',
    'modelNumber': 'Model Number',
    'originCountry': 'Country of Origin',
    'productCreated': 'Product created successfully!',
    'productUpdated': 'Product updated successfully!',
    'failedToCreateProduct': 'Failed to create product',
    'failedToUpdateProduct': 'Failed to update product',
    'productDeleted': 'Product deleted successfully',
    
    // New: Nav & Chrome
    'help': 'Help',
    'moreTools': 'More',
    'stock': 'Stock',
    'myShop': 'My Shop',
    'myOrders': 'My Orders',
    'tutorials': 'Tutorials',
    'payment': 'Payment',
    'coupons': 'Coupons',
    'inventory': 'Inventory',
    'general': 'General',
    'main': 'Main',
    'adminControls': 'Admin Controls',
    'wholesalerView': 'Wholesaler View',
    'sellerView': 'Seller View',
    'adminPanel': 'Admin Panel',
    'userManagement': 'User Management',
    'orderOversight': 'Order Oversight',
    'moderation': 'Moderation',
    'platformAnalytics': 'Platform Analytics',
    'tutorialManager': 'Tutorial Manager',
    'browseShopsNav': 'Browse Shops',
    'sellerOrders': 'Seller Orders',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
    
    // New: Auth
    'chooseBusinessRole': 'Choose Your Business Role',
    'selectHowToUse': 'Select how you want to use PakMandi',
    'wholesalerTitle': 'Wholesaler',
    'wholesalerDesc': 'Sell products to retailers across Pakistan',
    'wholesalerF1': 'Create and manage shops',
    'wholesalerF2': 'List unlimited products',
    'wholesalerF3': 'Create promotional ads',
    'wholesalerF4': 'Fulfill bulk orders',
    'sellerTitle': 'Seller/Retailer',
    'sellerDesc': 'Purchase from wholesalers and grow your business',
    'sellerF1': 'Browse wholesale catalogs',
    'sellerF2': 'Place bulk orders',
    'sellerF3': 'Track order status',
    'sellerF4': 'Manage inventory purchases',
    'selectedContinue': 'Selected',
    'businessVerification': 'Continue to business verification',
    'basicInformation': 'Continue to basic information',
    'wholesalerNote': 'Wholesalers need to provide business verification documents for security and trust.',
    'sellerNote': 'Sellers have a simplified registration process to get started quickly.',
    'note': 'Note',
    'pakistaniLogin': 'Pakistani Login',
    'enterMobileAndPassword': 'Enter your Pakistani mobile number and password',
    'pakistaniMobileLabel': 'Pakistani Mobile Number',
    'enterPassword': 'Enter your password',
    'signingIn': 'Signing In...',
    'signIn': 'Sign In',
    'or': 'Or',
    'createPakistaniAccount': 'Create Pakistani account',
    'secureAuth': 'Secure Authentication',
    'secureAuthDesc': 'Pakistani phone-only authentication with end-to-end encryption',
    'welcomeBack': 'Welcome back!',
    'loginSuccess': 'You have successfully logged in.',
    'needAccount': 'Need an Account?',
    'needAccountDesc': 'Create a new account to get started with our B2B marketplace.',
    'accountLocked': 'Account locked. Try again in {minutes} minutes.',
    'validPhoneError': 'Please enter a valid Pakistani mobile number (03XX-XXXXXXX)',
    'pakistaniAccount': 'Pakistani Account',
    'createB2BAccount': 'Create your Pakistani B2B business account',
    'businessTypeLabel': 'Business Type',
    'contactNameLabel': 'Contact Name',
    'yourFullName': 'Your full name',
    'businessNameLabel': 'Business Name',
    'yourBusinessName': 'Your business or shop name',
    'emailAddress': 'Email Address',
    'passwordLabel': 'Password',
    'createStrongPassword': 'Create a strong password',
    'weakPassword': 'Weak password',
    'mediumPassword': 'Medium strength',
    'strongPassword': 'Strong password',
    'agreeToTerms': 'I agree to the',
    'termsAndConditions': 'Terms & Conditions',
    'and': 'and',
    'creatingAccount': 'Creating Account...',
    'secureRegistration': 'Secure Registration',
    'secureRegDesc': 'Your data is protected with industry-standard encryption.',
    'alreadyHaveAccountLink': 'Already have an account?',
    'signInHere': 'Sign in here',
    'phoneAlreadyRegistered': 'Phone Already Registered',
    'phoneAlreadyDesc': 'This phone number is already registered. Please login instead.',
    'phoneAvailable': 'Phone number is available!',
    'phoneTaken': 'This phone number is already registered.',
    'loginInstead': 'Login instead?',
    'accountCreated': 'Account Created!',
    'checkEmailConfirm': 'Please check your email to confirm your account.',
    'signupFailed': 'Signup Failed',
    
    // New: Chat
    'pakMandiSupport': 'PakMandi Support',
    'aiAssistantOnline': 'AI Assistant • Online',
    'welcomeToSupport': 'Welcome to PakMandi Support!',
    'askAnything': 'Ask me anything about our B2B marketplace platform.',
    'quickQuestions': 'Quick Questions',
    'chatQ1': 'How do I create an ad?',
    'chatQ2': 'How to register as wholesaler?',
    'chatQ3': 'How does order processing work?',
    'chatQ4': 'What are the payment options?',
    'chatQ5': 'How to verify my business?',
    'loadingChatHistory': 'Loading chat history...',
    'typeYourMessage': 'Type your message...',
    'pressEnterToSend': 'Press Enter to send • Our AI assistant is here to help 24/7',
    'supportAssistant': 'Support Assistant',
    'typing': 'Typing...',
    
    // Chat Welcome
    'aiSupport': 'AI Support',
    'chatWelcomeIntro': "Hello! I'm your AI assistant for PakMandi. How can I help you today? You can ask me about:",
    'chatWelcomeQ1': 'How to create a shop',
    'chatWelcomeQ2': 'How to list products',
    'chatWelcomeQ3': 'How to create ads',
    'chatWelcomeQ4': 'How to switch roles',
    'chatWelcomeQ5': 'Any other platform-related questions',
  },
  ur: {
    // Navigation
    'welcome': 'خوش آمدید',
    'login': 'لاگ ان',
    'signup': 'سائن اَپ',
    'dashboard': 'ڈیش بورڈ',
    'products': 'مصنوعات',
    'orders': 'آرڈرز',
    'profile': 'پروفائل',
    'logout': 'لاگ آؤٹ',
    'home': 'ہوم',
    'shops': 'دکانیں',
    'features': 'خصوصیات',
    'blog': 'بلاگ',
    'about': 'ہمارے بارے میں',
    'messages': 'پیغامات',
    'favorites': 'پسندیدہ',
    'analytics': 'تجزیات',
    'settings': 'سیٹنگز',
    
    // Auth
    'email': 'ای میل',
    'password': 'پاس ورڈ',
    'phone': 'فون نمبر',
    'confirmPassword': 'پاس ورڈ کی تصدیق کریں',
    'forgotPassword': 'پاس ورڈ بھول گئے؟',
    'rememberMe': 'مجھے یاد رکھیں',
    'alreadyHaveAccount': 'پہلے سے اکاؤنٹ ہے؟',
    'dontHaveAccount': 'اکاؤنٹ نہیں ہے؟',
    'createAccount': 'اکاؤنٹ بنائیں',
    'loginToAccount': 'اپنے اکاؤنٹ میں لاگ ان کریں',
    
    // Roles
    'admin': 'ایڈمن',
    'wholesaler': 'ہول سیلر',
    'seller': 'فروخت کنندہ',
    'pending': 'زیر التواء',
    'selectRole': 'اپنا کردار منتخب کریں',
    
    // Featured Products
    'featuredProducts.title': 'نمایاں مصنوعات',
    'featuredProducts.description': 'پاکستان بھر میں تصدیق شدہ سپلائرز سے اعلیٰ معیار کی مصنوعات دریافت کریں',
    'featuredProducts.viewAll': 'تمام مصنوعات دیکھیں',
    'featuredProducts.sample': 'نمونہ',
    'featuredProducts.reviews': 'جائزے',
    'featuredProducts.moq': 'کم سے کم مقدار',
    'featuredProducts.viewDetails': 'تفصیلات دیکھیں',
    'featuredProducts.startJourney': 'اپنا کاروباری سفر شروع کریں',
    'featuredProducts.noProducts': 'کوئی نمایاں مصنوعات دستیاب نہیں',
    
    // Why Choose Us
    'whyChoose.title': 'پاک منڈی کیوں منتخب کریں؟',
    'whyChoose.description': 'خاص طور پر پاکستانی کاروباروں کے لیے مقامی ادائیگی کے طریقوں اور علاقائی مہارت کے ساتھ ڈیزائن کیا گیا',
    'whyChoose.wholesalers.title': 'تھوک فروشوں کے لیے',
    'whyChoose.wholesalers.description': 'دکانیں بنائیں، مصنوعات کی فہرست بنائیں، اور پاکستان بھر میں خوردہ فروشوں تک پہنچیں',
    'whyChoose.wholesalers.benefit1': 'لامحدود مصنوعات کی فہرست',
    'whyChoose.wholesalers.benefit2': 'جدید تجزیات',
    'whyChoose.wholesalers.benefit3': 'تشہیری اشتہارات',
    'whyChoose.sellers.title': 'بیچنے والوں کے لیے',
    'whyChoose.sellers.description': 'تصدیق شدہ تھوک فروشوں سے براہ راست معیاری مصنوعات حاصل کریں',
    'whyChoose.sellers.benefit1': 'بلک قیمتیں',
    'whyChoose.sellers.benefit2': 'تیز آرڈرنگ',
    'whyChoose.sellers.benefit3': 'انوینٹری کا انتظام',
    'whyChoose.secure.title': 'محفوظ تجارت',
    'whyChoose.secure.description': 'تصدیق شدہ کاروباروں اور محفوظ ادائیگیوں کے ساتھ مکمل سیکیورٹی',
    'whyChoose.secure.benefit1': 'کاروباری تصدیق',
    'whyChoose.secure.benefit2': 'محفوظ ادائیگیاں',
    'whyChoose.secure.benefit3': 'تنازعات کا حل',
    
    // Call to Action
    'cta.title': 'اپنے کاروبار کو تبدیل کرنے کے لیے تیار ہیں؟',
    'cta.description': 'پاکستان کی تیز ترین ترقی کرنے والی B2B مارکیٹ میں شامل ہوں۔ ہمارے سادہ رجسٹریشن عمل کے ساتھ منٹوں میں شروع کریں۔',
    'cta.createAccount': 'مفت اکاؤنٹ بنائیں',
    'cta.exploreMarketplace': 'مارکیٹ دریافت کریں',
    
    // Dashboard
    'totalOrders': 'کل آرڈرز',
    'pendingOrders': 'زیر التواء آرڈرز',
    'completedOrders': 'مکمل آرڈرز',
    'totalRevenue': 'کل آمدنی',
    'myShops': 'میری دکانیں',
    'myProducts': 'میری مصنوعات',
    'browseShops': 'دکانیں دیکھیں',
    'createShop': 'دکان بنائیں',
    'addProduct': 'پروڈکٹ شامل کریں',
    'viewAll': 'تمام دیکھیں',
    
    // Products
    'searchProducts': 'مصنوعات تلاش کریں...',
    'browseProducts': 'مصنوعات دیکھیں',
    'productName': 'پروڈکٹ کا نام',
    'price': 'قیمت',
    'quantity': 'مقدار',
    'category': 'زمرہ',
    'description': 'تفصیل',
    'addToCart': 'کارٹ میں شامل کریں',
    'outOfStock': 'اسٹاک ختم',
    'inStock': 'دستیاب',
    'minOrderQuantity': 'کم سے کم آرڈر کی مقدار',
    
    // Orders
    'orderDetails': 'آرڈر کی تفصیلات',
    'orderStatus': 'آرڈر کی صورتحال',
    'orderDate': 'آرڈر کی تاریخ',
    'deliveryAddress': 'ڈیلیوری کا پتہ',
    'paymentMethod': 'ادائیگی کا طریقہ',
    'totalAmount': 'کل رقم',
    'placeOrder': 'آرڈر دیں',
    'cancelOrder': 'آرڈر منسوخ کریں',
    'confirmOrder': 'آرڈر کی تصدیق کریں',
    'rejectOrder': 'آرڈر مسترد کریں',
    
    // Order Form
    'createOrder': 'آرڈر بنائیں',
    'productTotal': 'مصنوعات کی کل قیمت',
    'grandTotal': 'مجموعی کل',
    'buyerInformation': 'خریدار کی معلومات',
    'fullName': 'مکمل نام',
    'pakistaniMobileNumber': 'پاکستانی موبائل نمبر',
    'validPakistaniMobile': 'درست پاکستانی موبائل نمبر',
    'streetAddress': 'گلی کا پتہ',
    'shippingDetails': 'شپنگ کی تفصیلات',
    'shippingCost': 'شپنگ کی لاگت',
    'estimatedDelivery': 'تخمینی ترسیل',
    'standardShipping': 'معیاری شپنگ',
    'bankTransferDetails': 'بینک ٹرانسفر کی تفصیلات',
    'bank': 'بینک',
    'accountNumber': 'اکاؤنٹ نمبر',
    'accountTitle': 'اکاؤنٹ کا عنوان',
    'transferExactAmount': 'صحیح رقم (PKR {amount}) ٹرانسفر کریں اور نیچے ادائیگی کا اسکرین شاٹ اپ لوڈ کریں',
    'paymentScreenshot': 'ادائیگی کا اسکرین شاٹ',
    'clickToUpload': 'ادائیگی کا اسکرین شاٹ اپ لوڈ کرنے کے لیے کلک کریں',
    'maxFileSize': 'PNG, JPG {size} تک',
    'creatingOrder': 'آرڈر بنایا جا رہا ہے...',
    'enterFullName': 'اپنا مکمل نام درج کریں',
    'enterPhoneNumber': 'فون نمبر درج کریں',
    'enterStreetAddress': 'گلی کا پتہ درج کریں',
    'selectPaymentMethod': 'ادائیگی کا طریقہ منتخب کریں',
    'loadingPaymentMethods': 'ادائیگی کے طریقے لوڈ ہو رہے ہیں...',
    'noPaymentMethods': 'اس دکان کے لیے ادائیگی کے طریقے دستیاب نہیں ہیں۔ براہ کرم ادائیگی کے طریقے ترتیب دینے کے لیے ہول سیلر سے رابطہ کریں۔',
    'jazzcashDetails': 'جاز کیش کی تفصیلات',
    'easypaisaDetails': 'ایزی پیسہ کی تفصیلات',
    'mobileNumber': 'موبائل نمبر',
    'sendToJazzcash': 'اس جاز کیش نمبر پر PKR {amount} بھیجیں اور ادائیگی کا اسکرین شاٹ اپ لوڈ کریں',
    'sendToEasypaisa': 'اس ایزی پیسہ نمبر پر PKR {amount} بھیجیں اور ادائیگی کا اسکرین شاٹ اپ لوڈ کریں',
    'days': 'دن',
    
    // Shops
    'shopName': 'دکان کا نام',
    'shopAddress': 'دکان کا پتہ',
    'contactNumber': 'رابطہ نمبر',
    'businessType': 'کاروبار کی قسم',
    'postalCode': 'پوسٹل کوڈ',
    'city': 'شہر',
    'province': 'صوبہ',
    
    // Messages
    'typeMessage': 'اپنا پیغام ٹائپ کریں...',
    'send': 'بھیجیں',
    'newMessage': 'نیا پیغام',
    'conversations': 'گفتگو',
    
    // Common
    'save': 'محفوظ کریں',
    'cancel': 'منسوخ',
    'edit': 'ترمیم',
    'delete': 'حذف کریں',
    'search': 'تلاش',
    'filter': 'فلٹر',
    'sort': 'ترتیب',
    'loading': 'لوڈ ہو رہا ہے...',
    'error': 'خرابی',
    'success': 'کامیابی',
    'warning': 'انتباہ',
    'info': 'معلومات',
    'yes': 'ہاں',
    'no': 'نہیں',
    'confirm': 'تصدیق',
    'back': 'واپس',
    'next': 'اگلا',
    'previous': 'پچھلا',
    'submit': 'جمع کریں',
    'update': 'اپ ڈیٹ',
    'refresh': 'ریفریش',
    'downloadReport': 'رپورٹ ڈاؤن لوڈ کریں',
    'print': 'پرنٹ',
    'export': 'برآمد',
    'import': 'درآمد',
    
    // Shipping
    'shipping': 'شپنگ',
    'shippingConfiguration': 'شپنگ کی ترتیبات',
    'shippingMethod': 'شپنگ کی قیمت کا طریقہ',
    'flatRate': 'یکساں نرخ',
    'weightBased': 'وزن کی بنیاد پر',
    'cityBased': 'شہر کی بنیاد پر',
    'freeAboveAmount': 'مقررہ رقم سے زیادہ پر مفت',
    'flatRateCost': 'یکساں شپنگ کی قیمت',
    'freeShippingAbove': 'مفت شپنگ',
    'baseRate': 'بنیادی نرخ',
    'perKgRate': 'فی کلو نرخ',
    'estimatedDeliveryDays': 'تخمینہ ڈیلیوری کے دن',
    'expressShipping': 'تیز رفتار ڈیلیوری کا اختیار',
    'expressCost': 'تیز رفتار ڈیلیوری کی قیمت',
    'expressDeliveryDays': 'تیز رفتار ڈیلیوری کے دن',
    'enableShipping': 'شپنگ کی ترتیبات فعال کریں',
    'saveShippingConfig': 'شپنگ کی ترتیبات محفوظ کریں',
    'shippingConfigDescription': 'اپنی دکان کے لیے شپنگ کی قیمت کا حساب لگانے کی ترتیبات',
    'loadingShippingConfig': 'شپنگ کی ترتیبات لوڈ ہو رہی ہیں...',
    'saving': 'محفوظ ہو رہا ہے...',
    'noShopsYet': 'ابھی آپ کی کوئی دکان نہیں ہے۔ شپنگ کی ترتیبات کے لیے پہلے دکان بنائیں۔',
    
    // Languages
    'english': 'English',
    'urdu': 'اردو',
    
    // Footer
    'allRightsReserved': 'تمام حقوق محفوظ ہیں',
    'privacyPolicy': 'رازداری کی پالیسی',
    'termsOfService': 'سروس کی شرائط',
    'contactUs': 'ہم سے رابطہ کریں',
    
    // Dashboard Stats
    'totalProducts': 'کل مصنوعات',
    'activeOrders': 'فعال آرڈرز',
    'customers': 'گاہک',
    'ordersPlaced': 'آرڈرز دیے',
    'totalSpent': 'کل خرچ',
    'favoriteShops': 'پسندیدہ دکانیں',
    'totalUsers': 'کل صارفین',
    'platformRevenue': 'پلیٹ فارم آمدنی',
    'growthRate': 'ترقی کی شرح',
    'fromLastMonth': 'پچھلے مہینے سے',
    
    // Products
    'noProductsYet': 'ابھی کوئی مصنوعات نہیں',
    'startAddingProducts': 'اپنی دکان میں پہلی مصنوعات شامل کر کے شروع کریں۔',
    'hideInactiveProducts': 'غیر فعال مصنوعات چھپائیں',
    'showInactiveProducts': 'غیر فعال مصنوعات دکھائیں',
    'hide': 'چھپائیں',
    'show': 'دکھائیں',
    'inactive': 'غیر فعال',
    'approved': 'منظور شدہ',
    'rejected': 'مسترد',
    'unknown': 'نامعلوم',
    'failedToLoadProducts': 'مصنوعات لوڈ نہیں ہو سکیں',
    'moqPieces': 'کم سے کم مقدار: {moq} عدد',
    
    // Shops
    'noShopsFound': 'کوئی دکان نہیں ملی',
    'create': 'بنائیں',
    'createFirstShop': 'ہمارے پلیٹ فارم پر مصنوعات فروخت کرنے کے لیے اپنی پہلی دکان بنائیں۔',
    'createYourFirstShop': 'اپنی پہلی دکان بنائیں',
    'verified': 'تصدیق شدہ',
    'createNewShop': 'نئی دکان بنائیں',
    'enterShopName': 'دکان کا نام درج کریں',
    'enterCompleteAddress': 'دکان کا مکمل پتہ درج کریں',
    'shopLogo': 'دکان کا لوگو (اختیاری، زیادہ سے زیادہ 5MB)',
    'creating': 'بنایا جا رہا ہے...',
    'fileTooLarge': 'فائل بہت بڑی ہے',
    'logoMaxSize': 'لوگو تصویر 5MB سے کم ہونی چاہیے',
    'invalidFileType': 'غلط فائل قسم',
    'logoMustBeImage': 'لوگو تصویر فائل ہونی چاہیے',
    'shopCreatedSuccessfully': 'دکان کامیابی سے بنائی گئی!',
    'failedToCreateShop': 'دکان بنانا ناکام۔ دوبارہ کوشش کریں۔',
    'editShopDetails': 'دکان کی تفصیلات میں ترمیم',
    'selectCity': 'شہر منتخب کریں',
    'updating': 'اپ ڈیٹ ہو رہا ہے...',
    'updateShop': 'دکان اپ ڈیٹ کریں',
    'shopUpdated': 'دکان اپ ڈیٹ ہو گئی',
    'shopUpdatedSuccessfully': 'آپ کی دکان کی معلومات کامیابی سے اپ ڈیٹ ہو گئی ہیں۔',
    'failedToUpdateShop': 'دکان اپ ڈیٹ نہیں ہو سکی۔ دوبارہ کوشش کریں۔',
    'selectImageSmaller': 'براہ کرم 5MB سے چھوٹی تصویر منتخب کریں۔',
    'browseWholesaleShops': 'ہول سیل دکانیں دیکھیں',
    'discoverVerifiedSuppliers': 'پاکستان بھر میں تصدیق شدہ ہول سیل فراہم کنندگان دریافت کریں',
    'searchShops': 'نام، مقام یا رابطہ کے ذریعے دکانیں تلاش کریں...',
    'clear': 'صاف کریں',
    'loadingShops': 'دکانیں لوڈ ہو رہی ہیں...',
    'noShopsMatchSearch': 'آپ کی تلاش سے کوئی دکان میل نہیں کھاتی۔ مختلف الفاظ آزمائیں۔',
    'noShopsAvailable': 'اس وقت کوئی دکان دستیاب نہیں ہے۔',
    'viewProducts': 'مصنوعات دیکھیں',
    'productsAvailable': 'مصنوعات دستیاب ہیں',
    
    // Profile
    'myProfile': 'میری پروفائل',
    'manageAccountInfo': 'اپنے اکاؤنٹ کی معلومات اور ترجیحات کا نظم کریں',
    'completed': 'مکمل',
    'accountType': 'اکاؤنٹ کی قسم',
    
    // Orders
    'noOrders': 'ابھی کوئی آرڈر نہیں',
    'all': 'تمام',
    'attention': 'توجہ',
    'active': 'فعال',
    'confirmed': 'تصدیق شدہ',
    'shipped': 'بھیج دیا گیا',
    'delivered': 'پہنچا دیا گیا',
    'searchOrders': 'آرڈرز تلاش کریں...',
    'filterByStatus': 'حیثیت کے مطابق فلٹر کریں',
    'statusUpdated': 'حیثیت اپ ڈیٹ ہو گئی',
    'orderStatusChanged': 'آرڈر کی حیثیت {status} میں تبدیل ہو گئی',
    'failedToUpdateStatus': 'آرڈر کی حیثیت اپ ڈیٹ نہیں ہو سکی',
    'failedToFetchOrders': 'آرڈرز لانے میں ناکامی۔ دوبارہ کوشش کریں۔',
    
    // Analytics
    'overview': 'جائزہ',
    'detailed': 'تفصیلی',
    'performance': 'کارکردگی',
    'views': 'نظارے',
    'revenue': 'آمدنی',
    'dailyActivity': 'روزانہ سرگرمی',
    'ordersByStatus': 'حیثیت کے مطابق آرڈرز',
    'topProducts': 'سرفہرست مصنوعات',
    
    // Product Dialog
    'createProduct': 'مصنوعات بنائیں',
    'editProduct': 'مصنوعات میں ترمیم',
    'basicInfo': 'بنیادی معلومات',
    'detailedInfo': 'تفصیلی معلومات',
    'images': 'تصاویر',
    'variations': 'تغیرات',
    'pricing': 'قیمت',
    'uploadImages': 'تصاویر اپ لوڈ کریں',
    'selectShop': 'دکان منتخب کریں',
    'enterProductName': 'مصنوعات کا نام درج کریں',
    'enterPrice': 'قیمت درج کریں',
    'enterDescription': 'مصنوعات کی تفصیل درج کریں',
    'selectCategory': 'زمرہ منتخب کریں',
    'productActive': 'فعال',
    'moq': 'کم سے کم آرڈر کی مقدار (MOQ)',
    'brand': 'برانڈ',
    'modelNumber': 'ماڈل نمبر',
    'originCountry': 'ملک',
    'productCreated': 'مصنوعات کامیابی سے بنائی گئی!',
    'productUpdated': 'مصنوعات کامیابی سے اپ ڈیٹ ہو گئی!',
    'failedToCreateProduct': 'مصنوعات بنانا ناکام',
    'failedToUpdateProduct': 'مصنوعات اپ ڈیٹ ناکام',
    'productDeleted': 'مصنوعات کامیابی سے حذف ہو گئی',
    
    // New: Nav & Chrome
    'help': 'مدد',
    'moreTools': 'مزید',
    'stock': 'اسٹاک',
    'myShop': 'میری دکان',
    'myOrders': 'میرے آرڈرز',
    'tutorials': 'ٹیوٹوریلز',
    'payment': 'ادائیگی',
    'coupons': 'کوپنز',
    'inventory': 'گودام',
    'general': 'عام',
    'main': 'بنیادی',
    'adminControls': 'ایڈمن کنٹرولز',
    'wholesalerView': 'ہول سیلر ویو',
    'sellerView': 'فروخت کنندہ ویو',
    'adminPanel': 'ایڈمن پینل',
    'userManagement': 'صارفین کا انتظام',
    'orderOversight': 'آرڈرز کی نگرانی',
    'moderation': 'نگرانی',
    'platformAnalytics': 'پلیٹ فارم تجزیات',
    'tutorialManager': 'ٹیوٹوریل مینیجر',
    'browseShopsNav': 'دکانیں دیکھیں',
    'sellerOrders': 'فروخت کنندہ آرڈرز',
    'darkMode': 'ڈارک موڈ',
    'lightMode': 'لائٹ موڈ',
    
    // New: Auth
    'chooseBusinessRole': 'اپنا کاروباری کردار منتخب کریں',
    'selectHowToUse': 'پاک منڈی کیسے استعمال کرنا چاہتے ہیں؟',
    'wholesalerTitle': 'ہول سیلر (تھوک فروش)',
    'wholesalerDesc': 'پاکستان بھر میں خوردہ فروشوں کو سامان فروخت کریں',
    'wholesalerF1': 'دکانیں بنائیں اور چلائیں',
    'wholesalerF2': 'لامحدود مصنوعات شامل کریں',
    'wholesalerF3': 'اشتہارات بنائیں',
    'wholesalerF4': 'تھوک آرڈرز پورے کریں',
    'sellerTitle': 'خریدار / دکاندار',
    'sellerDesc': 'ہول سیلرز سے خریداری کریں اور کاروبار بڑھائیں',
    'sellerF1': 'ہول سیل کیٹلاگ دیکھیں',
    'sellerF2': 'تھوک آرڈرز دیں',
    'sellerF3': 'آرڈر کی صورتحال دیکھیں',
    'sellerF4': 'خریداری کا انتظام کریں',
    'selectedContinue': 'منتخب شدہ',
    'businessVerification': 'کاروباری تصدیق جاری رکھیں',
    'basicInformation': 'بنیادی معلومات جاری رکھیں',
    'wholesalerNote': 'ہول سیلرز کو حفاظت اور اعتماد کے لیے کاروباری تصدیقی دستاویزات فراہم کرنی ہوں گی۔',
    'sellerNote': 'خریداروں کے لیے آسان رجسٹریشن عمل ہے تاکہ فوری شروع کر سکیں۔',
    'note': 'نوٹ',
    'pakistaniLogin': 'لاگ ان کریں',
    'enterMobileAndPassword': 'اپنا پاکستانی موبائل نمبر اور پاس ورڈ درج کریں',
    'pakistaniMobileLabel': 'پاکستانی موبائل نمبر',
    'enterPassword': 'اپنا پاس ورڈ درج کریں',
    'signingIn': 'لاگ ان ہو رہا ہے...',
    'signIn': 'لاگ ان',
    'or': 'یا',
    'createPakistaniAccount': 'پاکستانی اکاؤنٹ بنائیں',
    'secureAuth': 'محفوظ تصدیق',
    'secureAuthDesc': 'پاکستانی فون نمبر سے محفوظ لاگ ان',
    'welcomeBack': '!خوش آمدید',
    'loginSuccess': 'آپ کامیابی سے لاگ ان ہو گئے ہیں۔',
    'needAccount': 'اکاؤنٹ چاہیے؟',
    'needAccountDesc': 'ہماری B2B مارکیٹ میں شروع کرنے کے لیے نیا اکاؤنٹ بنائیں۔',
    'accountLocked': 'اکاؤنٹ بند ہے۔ {minutes} منٹ بعد دوبارہ کوشش کریں۔',
    'validPhoneError': 'درست پاکستانی موبائل نمبر درج کریں (03XX-XXXXXXX)',
    'pakistaniAccount': 'پاکستانی اکاؤنٹ',
    'createB2BAccount': 'اپنا پاکستانی B2B کاروباری اکاؤنٹ بنائیں',
    'businessTypeLabel': 'کاروبار کی قسم',
    'contactNameLabel': 'رابطہ نام',
    'yourFullName': 'آپ کا پورا نام',
    'businessNameLabel': 'کاروبار کا نام',
    'yourBusinessName': 'آپ کے کاروبار یا دکان کا نام',
    'emailAddress': 'ای میل ایڈریس',
    'passwordLabel': 'پاس ورڈ',
    'createStrongPassword': 'مضبوط پاس ورڈ بنائیں',
    'weakPassword': 'کمزور پاس ورڈ',
    'mediumPassword': 'درمیانہ مضبوط',
    'strongPassword': 'مضبوط پاس ورڈ',
    'agreeToTerms': 'میں اس سے اتفاق کرتا ہوں',
    'termsAndConditions': 'شرائط و ضوابط',
    'and': 'اور',
    'creatingAccount': 'اکاؤنٹ بنایا جا رہا ہے...',
    'secureRegistration': 'محفوظ رجسٹریشن',
    'secureRegDesc': 'آپ کا ڈیٹا صنعتی معیار کی انکرپشن سے محفوظ ہے۔',
    'alreadyHaveAccountLink': 'پہلے سے اکاؤنٹ ہے؟',
    'signInHere': 'یہاں لاگ ان کریں',
    'phoneAlreadyRegistered': 'فون پہلے سے رجسٹرڈ ہے',
    'phoneAlreadyDesc': 'یہ فون نمبر پہلے سے رجسٹرڈ ہے۔ براہ کرم لاگ ان کریں۔',
    'phoneAvailable': 'فون نمبر دستیاب ہے!',
    'phoneTaken': 'یہ فون نمبر پہلے سے رجسٹرڈ ہے۔',
    'loginInstead': 'لاگ ان کریں؟',
    'accountCreated': 'اکاؤنٹ بن گیا!',
    'checkEmailConfirm': 'اپنا اکاؤنٹ تصدیق کرنے کے لیے ای میل چیک کریں۔',
    'signupFailed': 'سائن اپ ناکام',
    
    // New: Chat
    'pakMandiSupport': 'پاک منڈی سپورٹ',
    'aiAssistantOnline': 'AI معاون • آن لائن',
    'welcomeToSupport': 'پاک منڈی سپورٹ میں خوش آمدید!',
    'askAnything': 'ہماری B2B مارکیٹ کے بارے میں کچھ بھی پوچھیں۔',
    'quickQuestions': 'فوری سوالات:',
    'chatQ1': 'اشتہار کیسے بنائیں؟',
    'chatQ2': 'ہول سیلر کیسے بنیں؟',
    'chatQ3': 'آرڈر کا عمل کیسے ہوتا ہے؟',
    'chatQ4': 'ادائیگی کے کیا طریقے ہیں؟',
    'chatQ5': 'کاروبار کی تصدیق کیسے کریں؟',
    'loadingChatHistory': 'چیٹ لوڈ ہو رہی ہے...',
    'typeYourMessage': 'اپنا پیغام لکھیں...',
    'pressEnterToSend': 'بھیجنے کے لیے Enter دبائیں • AI معاون 24/7 دستیاب ہے',
    'supportAssistant': 'سپورٹ معاون',
    'typing': 'لکھ رہا ہے...',
    
    // Chat Welcome
    'aiSupport': 'AI سپورٹ',
    'chatWelcomeIntro': 'السلام علیکم! میں پاک منڈی کا AI معاون ہوں۔ آج میں آپ کی کیا مدد کر سکتا ہوں؟ آپ مجھ سے یہ پوچھ سکتے ہیں:',
    'chatWelcomeQ1': 'دکان کیسے بنائیں',
    'chatWelcomeQ2': 'مصنوعات کی فہرست کیسے بنائیں',
    'chatWelcomeQ3': 'اشتہار کیسے بنائیں',
    'chatWelcomeQ4': 'کردار کیسے تبدیل کریں',
    'chatWelcomeQ5': 'پلیٹ فارم سے متعلق کوئی بھی سوال',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // Get saved language from localStorage or default to 'en'
    return localStorage.getItem('language') || 'en';
  });

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    // Set document direction for RTL languages
    document.documentElement.dir = lang === 'ur' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  // Set initial direction
  React.useEffect(() => {
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
