// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://waysinevrvvikqooxyuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndheXNpbmV2cnZ2aWtxb294eXV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTEyODIsImV4cCI6MjA2MTU4NzI4Mn0.-MGngOp5A_5V5UXySrjpOcDj8scMIMARUakzxuiZjyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);